language: java

jdk:
  - openjdk11

script:
  - mvn -q -Dsonar.projectKey=warp10-java-client -Dsonar.organization=avalon-lab -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=integration clean install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
